baseurl = "https://www.ahsht.io/"
languageCode = "en-us"
title = "Ah, Sht"
theme = "theme"

[params]
	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Ah, Sht"

		[params.navigation.links]
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Sht Happens. Let's make the best of it."
		subtitle   = "Ah Sht is a set of services that is designed to help coordinate, remediate and understand software incidents."
		buttonText = "Get the Slack Bot"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "We just make a slack (or Google Chat) bot at the minute. You probably want that."

		[params.aside.button]
			text = "Take me to it"
			link = "https://slack.com/oauth/authorize?client_id=912229766149.912230012704&scope=bot"

	# Contact section
	[params.contact]
		headline = "Need some help?"
		description = "If you're stuck and otherwise need some guidance, shoot us an email"
		email = "support@ahsht.io"
